### ISSUE TITLE
Hello!  Also, UTF-16

### ISSUE THREAD

**Issue by zamicol** [cyberphone/ietf-json-canon#23]
Hello!

I noticed that the spec uses UTF-16 for ordering.  Why not just UTF-8 as [UTF-8 is the serialization format defined for JSON](https://datatracker.ietf.org/doc/html/rfc8259#section-8.1)?  Adding UTF-16 is an additional burden on JSON systems that only currently have to support UTF-8 to be JSON compliant.

**Comment by cyberphone** [comment]
Hi,
The RFC is as it is and there are many implementations.

This was a discussion point during development but UTF-16 is actually the internal string format in JavaScript, Java, and C# which was the reason for sticking to UTF-16.   `\uhhhh` constants are also in UTF-16 so JSON implementations need to understand that.  However, using UTF-8 for ordering will work in most real-world cases since nobody (in their right mind...) use anything but 7-bit ASCII for keys.

FWIW, I'm nowadays concentrating on CBOR since it doesn't need canonicalization:
https://github.com/cyberphone/cbor-everywhere#cbor-everywhere

**Comment by zamicol** [comment]
Thank you for your response.  

>\uhhhh constants are also in UTF-16

Could you clarify this for me?  I don't believe that's correct.  The \uhhhh constants are Unicode code points.  UTF-8 is Unicode, as well as UTF-32.  UTF-16 isn't required for UTF-8 to adhere to Unicode.

**Comment by cyberphone** [comment]
Well, JSON was initially derived from JavaScript which still uses UTF-16 elements to form strings.  So does Windows, C#, Java, and Kotlin.  To cover the full UTF-32 range these systems must sometimes use two 16-bit elements.  A JSON processor must thus understand UTF-16 in order to create proper UTF-8.  All Unicode representations are "by design" fully compatible in both directions so there is no hidden "problem" here.  Yes, some people didn't like this solution but even the author of the JSON RFC agreed that it works as I claimed.
